routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'view']);

Route::resource('posts', PostController::class);
Route::get('/view/{slug?}', [PostController::class, 'view'])->name('posts.view');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $table = 'posts';

    protected $fillable = [
        'title',
        'slug',
        'content',
        'published',
        'menu_index'
    ];

    public static function getMenuItems()
    {
        return Post::where('published', 1)->select('title', 'slug')->orderBy('menu_index', 'asc')->get();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;

class PostController extends Controller
{
    private $validationRules = [
        'title' => 'required|max:255',
        'slug' => ['required', 'max:255'],
        'content' => 'required',
        'menu_index' => 'numeric',
        'published' => 'boolean'
    ];

    private $message = 'Post %s successfully';

    public function __construct()
    {
        View::share('menuItems', Post::getMenuItems());

        $this->middleware('auth')->except('view');
    }

    public function view($slug = null)
    {
        $post = is_null($slug) ? Post::first() : Post::where('slug', $slug)->first();

        return view('posts.view')->with('post', $post);
    }

    public function index()
    {
        $posts = Post::all();

        return view('posts.index')->with('posts', $posts);
    }

    public function create()
    {
        return view('posts.upsert')->with('post', new Post());
    }

    public function store(Request $request)
    {
        array_push($this->validationRules['slug'], 'unique:posts');

        $request->validate($this->validationRules);

        Post::create($request->all());

        return redirect()->route('posts.index')->with('message', sprintf($this->message, 'created'));
    }

    public function show($id)
    {
        $post = Post::find($id);

        return view('posts.show')->with('post', $post);
    }

    public function edit($id)
    {
        $post = Post::find($id);

        return view('posts.upsert')->with('post', $post);
    }

    public function update(Request $request, $id)
    {
        array_push($this->validationRules['slug'], "unique:posts,slug,$id,id");

        $request->validate($this->validationRules);

        Post::find($id)->update($request->all());

        return redirect()->route('posts.index')->with('message', sprintf($this->message, 'updated'));
    }

    public function destroy($id)
    {
        Post::find($id)->delete();

        return redirect()->route('posts.index')->with('message', sprintf($this->message, 'deleted'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/cms-app.blade.php
<!DOCTYPE html>

<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        
        <meta charset="utf-8">
        
        <meta name="viewport" content="initial-scale=1, shrink-to-fit=no">

        <title>{{ config('app.name') }} | @yield('title')</title>

        <link rel="icon" type="image/x-icon" href="/favicon.ico">

        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
              crossorigin="anonymous">

        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
              integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
              crossorigin="anonymous">

        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&display=swap">

        <link rel="stylesheet" href="{{ asset('css/cms-app.css') }}">

    </head>

    <body>
        
        <header>

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            
                <a class="navbar-brand" href="/">
                    <img id="logo" src="/img/logo.png" alt="GeoPal">
                </a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-nav-dropdown" aria-controls="navbar-nav-dropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar-nav-dropdown">
                    
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        @isset($menuItems)
                            @foreach($menuItems as $menuItem)
                                <li class="nav-item">
                                    <a href="{{ route('posts.view', $menuItem->slug) }}" class="nav-link">{{ $menuItem->title }}</a>
                                </li>
                            @endforeach
                        @endisset
                    </ul>
                    
                    <ul class="navbar-nav my-2 my-lg-0">
                         @if(Route::has('login'))
               
                            @auth
                                <li class="nav-item">
                                    <a href="{{ route('posts.index') }}" class="nav-link">Dashboard</a>
                                </li>
                                
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf

                                    <li class="nav-item">
                                        <button type="submit" class="logout btn nav-link">Logout</button>
                                    </li>
                                </form>
                            @else
                                <li class="nav-item">
                                    <a href="{{ route('login') }}" class="nav-link">Login</a>
                                </li>

                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a href="{{ route('register') }}" class="nav-link">Register</a>
                                    </li>
                                @endif
                            @endif

                        @endif
                    </ul>

                </div>
            
            </nav>
            
        </header>

        <div class="container-fluid">

            <article>
                @if (Session::has('message'))
                    <div class="alert alert-success mb-4"><i class="fa fas fa-exclamation-triangle"></i> {{ Session::get('message') }}</div>
                @endif

                @yield('content')
            </article>

        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
                integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
                crossorigin="anonymous">
        </script>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
                crossorigin="anonymous">
        </script>

    </body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/posts/index.blade.php
@extends('layouts.cms-app')

@section('title')
    Posts
@endsection

@section('content')

    <a class="btn btn-success mb-4" href="{{ route('posts.create') }}">Create New Post</a>

    @if($posts->isNotEmpty())
        <table id="posts" class="table table-striped table-bordered table-hover w-100">
            <thead class="thead-dark">
                <tr>
                    <th width="5%">ID</th>
                    <th width="10%">Title</th>
                    <th width="10%">Slug</th>
                    <th width="33%">Content</th>
                    <th width="5%">Published</th>
                    <th width="7%">Menu Index</th>
                    <th width="10%">Created</th>
                    <th width="10%"></th>
                </tr>
            </thead>
            <tbody>
                @foreach($posts as $post)
                    <tr>
                        <td>{{ $post->id }}</td>
                        <td>{{ $post->title }}</td>
                        <td>{{ $post->slug }}</td>
                        <td>{{ Str::of($post->content)->limit(400) }}</td>
                        <td>{{ $post->published ? 'Yes' : 'No' }}</td>
                        <td>{{ $post->menu_index }}</td>
                        <td>{{ date_format($post->created_at, 'jS M Y') }}</td>
                        <td>
                            <div class="dropdown">
                                
                                <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="actions-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Actions
                                </button>
                                
                                <div class="dropdown-menu" aria-labelledby="actions-dropdown">
                                    <a class="dropdown-item" href="{{ route('posts.view', $post->slug) }}"><i class="fa fas fa-external-link-alt"></i> View</a>
                                    
                                    <a class="dropdown-item" href="{{ route('posts.show', $post->id) }}"><i class="fa far fa-eye"></i> Show more</a>

                                    <a class="dropdown-item" href="{{ route('posts.edit', $post->id) }}"><i class="fa fas fa-edit"></i> Edit</a>
                                    
                                    <form action="{{ route('posts.destroy', $post->id) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="dropdown-item"><i class="fa far fa-trash-alt"></i> Delete</button>
                                    </form>
                                </div>

                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <h2>No posts to display.</h2>
        <p>Would you like to <a href="{{ route('posts.create') }}">create a new post</a>?</p>
    @endif

@endsection

resources/views/posts/show.blade.php
@extends('layouts.cms-app')

@section('title')
    {{ $post ? "Viewing $post->title" : 'Post not found' }}
@endsection

@section('content')

    <a class="btn btn-secondary mb-4" href="{{ route('posts.index') }}"><i class="fas fa-arrow-left"></i> All Posts</a>
            
    @if($post)
        <table class="table table-bordered">
            <tr>
                <td width="200"><strong>Title:</strong></td>
                <td>{{ $post->title }}</td>
            </tr>
            <tr>
                <td><strong>Content:</strong></td>
                <td>{{ $post->content }}</td>
            </tr>
            <tr>
                <td><strong>Published:</strong></td>
                <td>{{ $post->published ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <td><strong>Date Created:</strong></td>
                <td>{{ date_format($post->created_at, 'jS M Y') }}</td>
            </tr>
        </table>
    @else
        <h2>Post not found.</h2>
    @endif

@endsection

resources/views/posts/upsert.blade.php
@extends('layouts.cms-app')

@if($post)
    @section('title')
        {{ $post->exists ? 'Edit Post' : 'Add Post' }}
    @endsection

    @section('content')
        <div class="row">
            
            <div class="col-lg-12">
                <a class="btn btn-secondary mb-4" href="{{ route('posts.index') }}"><i class="fas fa-arrow-left"></i> All Posts</a>
                <h2>{{ $post->exists ? 'Edit Post' : 'Create a New Post' }}</h2>
            </div>

            @if($errors->any())
                <div class="col-sm-6">
                    <div class="alert alert-danger">
                        <p><strong>There were some problems saving your content:</strong></p>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif

        </div>

        <form action="{{ $post->exists ? route('posts.update', $post->id) : route('posts.store') }}" method="POST">
            
            @csrf

            @if($post->exists)
                @method('PATCH')
            @endif

            <div class="row">
                
                <div class="col-sm-6">
                    
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" value="{{ old('title', $post->title) }}" class="form-control" placeholder="Title">
                    </div>

                    <div class="form-group">
                        <label for="slug">Slug</label>
                        <input type="text" name="slug" id="slug" value="{{ old('slug', $post->slug) }}" class="form-control" placeholder="Slug">
                    </div>

                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea name="content" id="content" rows="15" class="form-control" placeholder="Content">{{ old('content', $post->content) }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="menu-index">Menu Index</label>
                        <select name="menu_index" id="menu-index" class="form-control">
                            @foreach (range(1, 10) as $menuIndex)
                                <option value="{{ $menuIndex }}" {{ ($menuIndex == old('menu-index', $post->menu_index)) ? 'selected' : '' }}>{{ $menuIndex }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-check form-group">
                        <input type="checkbox" name="published" id="published" value="1" {{ old('published', $post->published) || !$post->exists ? 'checked' : '' }} class="form-check-input">
                        <label for="published" class="form-check-label">Published</label>
                    </div>

                    <button type="submit" class="btn btn-success">Save</button>

                </div>

            </div>

        </form>
    @endsection
@else
    @section('title')
        Post not found
    @endsection

    @section('content')
        <h2>Post not found.</h2>
    @endsection
@endif

resources/views/posts/view.blade.php
@extends('layouts.cms-app')

@section('title')
    {{ $post ? $post->title : 'Post not found' }}
@endsection

@section('content')
    @if($post)
        <h1>{{ $post->title }}</h1>
        <p class="text-secondary">Last Updated: {{ date_format($post->updated_at, 'jS F Y') }}</p>
        {!! Str::of($post->content)->markdown() !!}
    @else
        <h2>The post you requested could not be found.</h2>
    @endif
@endsection